# Generated by Django 2.1.1 on 2019-11-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_id', models.IntegerField(default='', unique=True)),
                ('kanji', models.CharField(default='', max_length=255)),
                ('kana_reading', models.CharField(max_length=255, null=True)),
                ('meaning', models.CharField(max_length=512, null=True)),
                ('word_type', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
