# Generated by Django 2.1.1 on 2019-11-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nihongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('grammar_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='id',
        ),
        migrations.AlterField(
            model_name='word',
            name='word_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
