# Generated by Django 2.1.1 on 2019-11-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nihongo', '0002_auto_20191105_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarpoint',
            name='sample_sentence',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
