# Generated by Django 2.1 on 2018-09-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, default='', max_length=10)),
                ('tran_date', models.DateTimeField(blank=True, default='')),
                ('price_open', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('price_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('price_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('price_close', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
        ),
    ]
