# Generated by Django 2.1 on 2018-09-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default='')),
                ('current_assets', models.CharField(default='', max_length=30)),
                ('total_assets', models.CharField(default='', max_length=30)),
                ('current_liabilites', models.CharField(default='', max_length=30)),
                ('total_liabilities', models.CharField(default='', max_length=30)),
                ('retained_earnings', models.CharField(default='', max_length=30)),
                ('stock_holders_equity', models.CharField(default='', max_length=30)),
                ('equity_parent', models.CharField(default='', max_length=30)),
                ('bvps', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRatioRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default='')),
                ('current_ratio', models.CharField(default='', max_length=30)),
                ('quick_ratio', models.CharField(default='', max_length=30)),
                ('solvency_ratio', models.CharField(default='', max_length=30)),
                ('debt_ratio', models.CharField(default='', max_length=30)),
                ('de_ratio', models.CharField(default='', max_length=30)),
                ('int_coverage_ratio', models.CharField(default='', max_length=30)),
                ('asset_ratio', models.CharField(default='', max_length=30)),
                ('gross_profit_margin', models.CharField(default='', max_length=30)),
                ('net_profit_margin', models.CharField(default='', max_length=30)),
                ('roa', models.CharField(default='', max_length=30)),
                ('roe', models.CharField(default='', max_length=30)),
                ('pe_ratio', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10)),
                ('date', models.DateField(default='')),
                ('operating_revenue', models.CharField(default='', max_length=30)),
                ('other_revenue', models.CharField(default='', max_length=30)),
                ('gross_revenue', models.CharField(default='', max_length=30)),
                ('gross_expense', models.CharField(default='', max_length=30)),
                ('non_operating_income', models.CharField(default='', max_length=30)),
                ('non_operating_expense', models.CharField(default='', max_length=30)),
                ('income_loss_before_tax', models.CharField(default='', max_length=30)),
                ('income_tax_expense', models.CharField(default='', max_length=30)),
                ('net_income_after_tax', models.CharField(default='', max_length=30)),
                ('net_income_to_parent', models.CharField(default='', max_length=30)),
                ('eps_basic', models.CharField(default='', max_length=30)),
                ('eps_diluted', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=10)),
                ('tran_date', models.DateField(default='')),
                ('price_open', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('price_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('price_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('price_close', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('volume', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_high',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_low',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_open',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='tran_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='', max_length=10),
        ),
    ]
