# Generated by Django 2.1.1 on 2018-11-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0004_auto_20181109_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='price_close',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='record',
            name='price_high',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='record',
            name='price_low',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='record',
            name='price_open',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=19),
        ),
    ]
