# Generated by Django 2.1.1 on 2018-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0005_auto_20181109_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
